// components/Rating.vue
<template>
  <div class="rating mb-4">
    <div class="rating__image">
      <nuxt-picture
        :src="review.image"
        :alt="review.title"
        width="365"
        height="365"
      />
    </div>
    <div class="rating__overall">
      <p class="rating__score">
        {{
          review.rating.lyrics +
          review.rating.production +
          review.rating.replayValue +
          review.rating.variety
        }}
        / 100
      </p>
      <p class="rating__name">Overall</p>
    </div>
    <div class="rating__category">
      <p class="rating__score">{{ review.rating.lyrics }}<span> / 35</span></p>
      <p class="rating__name">Lyrics</p>
    </div>
    <div class="rating__category">
      <p class="rating__score">
        {{ review.rating.production }}
        / 35
      </p>
      <p class="rating__name">Production</p>
    </div>
    <div class="rating__category">
      <p class="rating__score">
        {{ review.rating.replayValue }}
        / 15
      </p>
      <p class="rating__name">Replay Value</p>
    </div>
    <div class="rating__category">
      <p class="rating__score">
        {{ review.rating.variety }}
        / 15
      </p>
      <p class="rating__name">Variety</p>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    review: {
      type: Object,
      required: true,
    },
  },
}
</script>

<style></style>

// src/components/Rating/Rating.tsx
import Image from "next/image";
import styles from "./Rating.module.scss";

interface RatingProps {
  lyrics: number;
  production: number;
  replayValue: number;
  variety: number;
  image: string;
  title: string;
}

const Rating = ({
  lyrics,
  production,
  replayValue,
  variety,
  image,
  title,
}: RatingProps) => {
  return (
    <div className="rating mb-4">
      <div className="rating__image">
        <Image
          src={`/images/${image}`}
          alt={`Album cover for ${title}`}
          width={400}
          height={400}
        />
      </div>
      <div className="rating__overall">
        <p className="rating__score">
          {lyrics + production + replayValue + variety} / 100
        </p>
        <p className="rating__name">Overall</p>
      </div>
      <div className="rating__category">
        <p className="rating__score">
          {lyrics}
          <span> / 35</span>
        </p>
        <p className="rating__name">Lyrics</p>
      </div>
      <div className="rating__category">
        <p className="rating__score">{production}/ 35</p>
        <p className="rating__name">Production</p>
      </div>
      <div className="rating__category">
        <p className="rating__score">{replayValue}/ 15</p>
        <p className="rating__name">Replay Value</p>
      </div>
      <div className="rating__category">
        <p className="rating__score">{variety}/ 15</p>
        <p className="rating__name">Variety</p>
      </div>
    </div>
  );
};

export default Rating;
