// src/pages/reviews/index.tsx
import { getReviewPostsData } from "@/lib/posts";
import FeaturedPosts from "@/src/components/FeaturedPosts";
import Header from "@/src/components/Header";
import PreviewCard from "@/src/components/PreviewCard";
import { GetStaticProps } from "next";
import { NextSeo } from "next-seo";

interface ReviewPageProps {
  reviews: Array<any>;
}

export const getStaticProps: GetStaticProps = async () => {
  let reviews = getReviewPostsData();
  reviews = JSON.parse(JSON.stringify(reviews));

  return {
    props: {
      reviews,
    },
  };
};

const Reviews = ({ reviews }: ReviewPageProps) => {
  const featuredReviews = reviews.filter(
    (review) => review.params.featured === true
  );
  const latestReviews = reviews
    .filter(
      (review) =>
        review.params.featured !== true && review.params.draft === false
    )
    .sort();
  return (
    <>
      <NextSeo
        title="Reviews"
        description="Hip hop album reviews for underground projects."
        openGraph={{
          url: "https://www.hiphopseason.com/reviews",
        }}
        canonical="https://www.hiphopseason.com/reviews"
      />
      <Header type="small" title="Reviews" image="review-header.jpg">
        <p className="lead">
          My thoughts and opinions about different albums and mixtapes.
        </p>
      </Header>
      <section>
        <div className="container">
          <FeaturedPosts posts={featuredReviews} />
        </div>
      </section>
      <section>
        <div className="container">
          <h2>All Reviews</h2>
          {latestReviews.map((review) => {
            return (
              <PreviewCard
                orientation="horizontal"
                key={review.params.id}
                post={review}
              />
            );
          })}
        </div>
      </section>
    </>
  );
};

export default Reviews;

// pages/reviews/index.vue
<template>
  <main>
    <PageHeader
      title="Reviews"
      subtitle="My thoughts and opinions about different albums and mixtapes."
    />
    <section>
      <div class="container">
        <h2 class="mb-4">Latest Reviews</h2>
        <div class="featured-container">
          <PreviewCardVertical
            v-for="review in latestReviews"
            :key="review.slug"
            :card="review"
          />
        </div>
      </div>
    </section>
    <section>
      <div class="container">
        <h2 class="mb-4">All Reviews</h2>
        <div class="card-list">
          <PreviewCardHorizontal
            v-for="review in allReviews"
            :key="review.slug"
            :card="review"
          />
        </div>
      </div>
    </section>
  </main>
</template>

<script>
import getMetaData from '@/config/getMetaData'

export default {
  async asyncData({ $content }) {
    const latestReviews = await $content('reviews')
      .where({ draft: false })
      .limit(2)
      .fetch()
    const allReviews = await $content('reviews')
      .where({ draft: false })
      .skip(2)
      .fetch()

    return { latestReviews, allReviews }
  },
  head() {
    return {
      title: 'Reviews',
      meta: [...this.meta],
      link: [
        {
          hid: 'canonical',
          rel: 'canonical',
          href: `https://hiphopseason.com/reviews`,
        },
      ],
    }
  },
  computed: {
    meta() {
      const metaData = {
        type: 'page',
        url: `https://hiphopseason.com/reviews`,
        title: 'Reviews',
        description: 'Hip hop album reviews for non-mainstream projects.',
      }

      return getMetaData(metaData)
    },
  },
}
</script>
